README.md
=> SDK-616/ Add security email in read me file

.github/workflows/release.yml
=> SDK-791/Add credentials to fix failing tests in public release

pom.xml
=> SDK-791/ Fix GPG key error in release

README.md
=> SDK-792/ Update Java SDK version in README

README.md
=> SDK-792/ Update README with default time to live value

samples/pom.xml, samples/src/main/java/com/example/GetExample.java
Added Sample Code for Get method in Java SDK
=> SK-304 Add sample for Get method in JAVA SDK

README.md
"recordsArrayJson" was "recordsArray".
=> DOC-383 Fixed "recordsArrayJson" typo in GetById example.

CHANGELOG.md, README.md
- Update CHANGELOG till latest version `v1.18.2`
- Update latest version in README
=> SK-660 Update CHANGELOG with latest version release in all SDKs

src/main/java/com/skyflow/entities/DetokenizeRecord.java, src/main/java/com/skyflow/logs/ErrorLogs.java, src/main/java/com/skyflow/vault/Detokenize.java, src/test/java/com/skyflow/vault/SkyflowTest.java
- SK-744 Development of Column Group Support in Java SDK
- SK-745 Unit Tests for Column Group Support in Java SDK
=> SK-340 Column Group Support in Java SDK

CHANGELOG.md, README.md, samples/pom.xml, samples/src/main/java/com/example/DetokenizeExample.java
- SK-747 Update `README` for Column Group Support changes in Java SDK
- SK-797 Update Sample for `Detokenize` w.r.t Column Group Support changes in Java SDK
=> SK-340 Update README, CHANGELOG, Samples for Column Group Support in Java SDK

src/main/java/com/skyflow/common/utils/TokenUtils.java, src/main/java/com/skyflow/vault/Skyflow.java, src/test/java/com/skyflow/common/utils/TokenUtilsTest.java
- Fixed bug where same token was being used for multiple skyflow client instances
=> SK-1212 Fix Java SDK bug

CHANGELOG.md, README.md, samples/src/main/java/com/example/InsertWithContinueOnErrorExample.java
- SK-1361 Add README, CHANGELOG & Samples for continue on error in batch Insert
=> SK-1361 Add continue on error in batch Insert

.github/workflows/codeql-analysis.yml, .github/workflows/codeql.yml, .github/workflows/main.yml, README.md, pom.xml, samples/README.md
To change default branch as main from master.
Made changes to workflow files to change the branch from master to main
=> SK-1573 update master to main branch as default

.semgreprules/customRule.yml
adding the custom rule of the semgrep to this repository
=> SC-3101:Create customRule.yml

.github/workflows/semgrep.yml
Implementing Semgrep which is a SAST for this repository
=> SC-3101:Create semgrep.yml

v2/src/main/java/com/skyflow/errors/ErrorCode.java, v2/src/main/java/com/skyflow/logs/ErrorLogs.java
Add error codes and messages
Add logs
=> SK-1682 add error codes, messages and logs

v2/src/main/java/com/skyflow/Skyflow.java, v2/src/main/java/com/skyflow/VaultClient.java, v2/src/main/java/com/skyflow/config/VaultConfig.java, v2/src/main/java/com/skyflow/enums/Byot.java, v2/src/main/java/com/skyflow/enums/Env.java, v2/src/main/java/com/skyflow/errors/SkyflowException.java, v2/src/main/java/com/skyflow/serviceaccount/util/BearerToken.java, v2/src/main/java/com/skyflow/utils/ColumnValue.java, v2/src/main/java/com/skyflow/utils/Constants.java, v2/src/main/java/com/skyflow/utils/Utils.java, v2/src/main/java/com/skyflow/utils/validations/Validations.java, v2/src/main/java/com/skyflow/vault/controller/VaultController.java, v2/src/main/java/com/skyflow/vault/data/DeleteRequest.java, v2/src/main/java/com/skyflow/vault/data/DeleteResponse.java, v2/src/main/java/com/skyflow/vault/data/GetRequest.java, v2/src/main/java/com/skyflow/vault/data/GetResponse.java, v2/src/main/java/com/skyflow/vault/data/InsertRequest.java, v2/src/main/java/com/skyflow/vault/data/InsertResponse.java, v2/src/main/java/com/skyflow/vault/data/QueryRequest.java, v2/src/main/java/com/skyflow/vault/data/QueryResponse.java, v2/src/main/java/com/skyflow/vault/data/UpdateRequest.java, v2/src/main/java/com/skyflow/vault/data/UpdateResponse.java, v2/src/main/java/com/skyflow/vault/tokens/ColumnValue.java, v2/src/main/java/com/skyflow/vault/tokens/DetokenizeRecordResponse.java, v2/src/main/java/com/skyflow/vault/tokens/DetokenizeRequest.java, v2/src/main/java/com/skyflow/vault/tokens/DetokenizeResponse.java, v2/src/main/java/com/skyflow/vault/tokens/TokenizeRequest.java, v2/src/main/java/com/skyflow/vault/tokens/TokenizeResponse.java
To improve the Skyflow SDKs in terms of Developer Experience (DevEx), performance, efficiency, security, error handling, logging, compatibility, and versioning, we have developed a new design for the V2 implementation of the SDKs. This design needs to be implemented according to best practices, language-specific nuances, and design patterns to ensure that the SDKs are extendable, more efficient, and developer-friendly.
- Implemented `insert` vault API public interface
- Implemented `get` vault API public interface
- Implemented `detokenize` vault API public interface
- Implemented `tokenize` vault API public interface
- Implemented `update` vault API public interface
- Implemented `query` vault API public interface
- Implemented `delete` vault API public interface
=> SK-1664 Implement vault API Public Interfaces

.github/workflows/internal-release.yml
To test the auto update of pom.xml with release version
=> SK-1753 auto generate release version in pom.xml

scripts/bump_version.sh
- To trigger the internal release - JAVA SDK v2
=> SK-1770 internal release of java sdk v2

README.md
**What?**
This PR updates the README documentation for Java SDK v2. The new README includes detailed instructions and examples for client initialization, configuration options, and vault api usage. It reflects the enhanced flexibility, modularity, and best practices implemented in SDK v2.
**Why?**
The previous README was tailored for Java SDK v1 and did not adequately cover the new features and options introduced in v2.
**How?**
- Updated the README to showcase examples of initializing clients with different configurations and vault api usage.
- Ensured the README aligns with Idiomatic approach and principles adopted in SDK v2, including modularity and clarity.
- Simplified complex scenarios with step-by-step instructions and relevant code snippets.
=> SK-1750 Rewrited README for SDK v2

README.md
This PR contains updated README content for SDK v2.
- The previous README for SDK v2 became outdated as we received feedback to improve it.
- The updated README will provide a clear and accurate representation of the v2 SDK’s improving developer understanding and usability.
=> SK-1893 Update README for v2

.github/workflows/semgrep.yml
This workflow automatically runs Semgrep scans on pull requests to identify security vulnerabilities. All findings are displayed in the build log for review.
If any issues are detected, a comment is posted directly on the PR.
=> SC-5146:Update semgrep.yml

src/main/java/com/skyflow/errors/SkyflowException.java
This PR addresses feedback as well as customer request for invoke connections. 
- When invoke connection request fails, the SDK throws an error with relevant details received from the API.
- However, the customer is unable to debug whether error occurred on their end or third-party end based on given info.
- Customers should be easily able to debug whether an error occurred on their end or third-party end
- Improved error response structure to help customers with their problem
- The changed were tested manually
=> SK-1900 Improve debugging errors in connections

v3/src/main/java/com/skyflow/utils/validations/Validations.java, v3/src/main/java/com/skyflow/vault/controller/VaultController.java, v3/src/main/java/com/skyflow/vault/data/DetokenizeRequest.java, v3/src/main/java/com/skyflow/vault/data/DetokenizeResponse.java
Why: 
Need to return failed tokens list when get retry tokens is called
=> SK-2274 add retry tokens fn

common/pom.xml, common/src/main/java/com/skyflow/logs/InfoLogs.java, common/src/main/java/com/skyflow/logs/WarningLogs.java, v2/pom.xml, v3/pom.xml, v3/src/main/java/com/skyflow/utils/Constants.java, v3/src/main/java/com/skyflow/vault/controller/VaultController.java
add warn log for max batch size and concurrency limit
=> SK-2274 release/25.9.2
