skyflowapi/skyflow-java

src/main/java/com/skyflow/common/utils/TokenUtils.java
- Removed 5 mins of grace period for cache refresh of bearer token
- Issue [SK-546](https://skyflow.atlassian.net/browse/SK-546)
[SK-546]: https://skyflow.atlassian.net/browse/SK-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-546 Removal of Grace Period of 5 mins

.github/workflows/internal-release.yml, .github/workflows/release.yml, pom.xml
1. Added the internal release workflow file
2. On merging the PR, internal release will be triggered
3. Modified pom.xml to have multiple distribution Managements
=> SK-1752 workflow for internal release

.github/workflows/internal-release.yml
Included create env step where we add SKYFLOW_CREDENTIALS and TEST_EXPIRED_TOKEN from secrets,
which we use to run unit tests
=> SK-1753 add create env step

.github/workflows/internal-release.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/shared-build-and-deploy.yml, pom.xml, scripts/bump_version.sh
- Add a common workflow file for both internal and public release
- This is to avoid code duplication
=> SK-1786 common workflow for internal and public release

src/main/java/com/skyflow/Skyflow.java, src/main/java/com/skyflow/utils/HttpUtility.java, src/main/java/com/skyflow/utils/validations/Validations.java, src/main/java/com/skyflow/vault/connection/InvokeConnectionResponse.java, src/main/java/com/skyflow/vault/controller/ConnectionController.java, src/test/java/com/skyflow/SkyflowTests.java, src/test/java/com/skyflow/vault/connection/InvokeConnectionTests.java, src/test/java/com/skyflow/vault/controller/ConnectionControllerTests.java
This PR includes changes to fix inconsistencies with respect to other server-side SDKs, some missing validation scenario along with additional unit tests.
- Java SDK v2 has some inconsistencies that needs to be addressed.
- To ensure consistent behaviour across server-side SDKs.
- Fewer inconsistencies w.r.t other server-side SDKs. 
- Consistent response structure for invoke connection response.
- Manual testing for all vault API interfaces along with connections.
- Additional unit tests for fixed inconsistencies.
=> SK-1737 Fix inconsistencies in Java SDK

.github/workflows/endorlabsScan.yml
Added a workflow to trigger endor labs scan on skyflow-java repository.
- There is a need to monitor different branches in skyflow-java repository on endor labs.
- To be able to monitor all branches of skyflow-java repository on endor labs
=> SK-1633 Run Endor labs scan to identify security vulnerabilities

.github/workflows/endorlabsScan.yml
Add a missing step to create `credentials.json` file in endor labs workflow
- The missing step caused some unit test failures while running the workflow.
- Fix unit test failures due to missing step
=> SK-1633 Fix failure in endorlabs workflow

.github/workflows/endorlabsScan.yml
Add GPG secrets to `endorlabsScan.yml` workflow.
- Due to missing gpg secrets, the workflow was failing in CI pipeline.
- Fix failures in workflow run
=> SK-1633 Add GPG secrets to endorlabs workflow

.github/workflows/endorlabsScan.yml
Change compile command in `endorlabsScan.yml` workflow.
- The previous command was failing while building the package in CI pipeline.
- Fix failures in workflow runs.
=> SK-1633 Fix failures in workflow

.github/workflows/endorlabsScan.yml
Added permissions for endrolabs to scan the repo
- The workflow for endorlabs scan was failing. 
- To fix the failure in `endorlabsScan.yml` workflow
=> SK-1633 Add permissions for endorlabs scan

.github/workflows/beta-release.yml, .github/workflows/internal-release.yml, .github/workflows/release.yml, .github/workflows/shared-build-and-deploy.yml
- To add a beta release workflow
- To make a beta release for sdk v2 changes
=> SK-1815 workflow for beta release

src/main/java/com/skyflow/errors/HttpStatus.java, src/main/java/com/skyflow/errors/SkyflowException.java, src/main/java/com/skyflow/utils/HttpUtility.java, src/main/java/com/skyflow/vault/connection/InvokeConnectionResponse.java, src/main/java/com/skyflow/vault/controller/ConnectionController.java, src/test/java/com/skyflow/utils/HttpUtilityTests.java, src/test/java/com/skyflow/vault/connection/InvokeConnectionTests.java, src/test/java/com/skyflow/vault/controller/VaultControllerTests.java
This PR adds an enum for default Http status in validation errors thrown by Java SDK. It also fixes issues in invoke connection flow for outbound connections.
- Added default Http status for SDK side validation errors.
- Fixed outbound connection flow for invoke connection.
- Fixed error handling in invoke connection.
- Will add default Http status for SDK side validation errors.
- Will remove issues with invoke connection flow.
- Will help in reducing inconsistencies and failures in E2E tests.
- Fixed failing test cases due to this changes introduced.
- Covered the newly added enum in unit tests.
=> SK-1829 Fix http status for validation errors in Java SDK v2

pom.xml, src/main/java/com/skyflow/errors/HttpStatus.java, src/main/java/com/skyflow/errors/SkyflowException.java, src/main/java/com/skyflow/utils/HttpUtility.java, src/main/java/com/skyflow/vault/connection/InvokeConnectionResponse.java, src/main/java/com/skyflow/vault/controller/ConnectionController.java, src/test/java/com/skyflow/utils/HttpUtilityTests.java, src/test/java/com/skyflow/vault/connection/InvokeConnectionTests.java, src/test/java/com/skyflow/vault/controller/VaultControllerTests.java
This PR adds an enum for default Http status in validation errors thrown by Java SDK. It also fixes issues in invoke connection flow for outbound connections.
- Added default Http status for SDK side validation errors.
- Fixed outbound connection flow for invoke connection.
- Fixed error handling in invoke connection.
- Will add default Http status for SDK side validation errors.
- Will remove issues with invoke connection flow.
- Will help in reducing inconsistencies and failures in E2E tests.
- Fixed failing test cases due to this changes introduced.
- Covered the newly added enum in unit tests.
=> SK-1829/Release/25.1.1

.github/workflows/shared-build-and-deploy.yml
- The current release pipelines for the Java SDK contain several repetitive steps within the workflows.
- These redundancies not only cause inefficiencies but also make it harder to maintain and debug the pipelines effectively.
- Reduced execution time by removing redundant steps.
- Creating reusable components will ensure that all workflows follow best practices and are easier to maintain moving forward.
=> SK-1820 refactor release pipeline

src/main/java/com/skyflow/utils/Constants.java, src/main/java/com/skyflow/vault/controller/VaultController.java, src/main/java/com/skyflow/vault/tokens/DetokenizeRecordResponse.java, src/test/java/com/skyflow/vault/data/InsertTests.java, src/test/java/com/skyflow/vault/tokens/DetokenizeTests.java
This PR addresses feedback for `insert` and `detokenize` methods SDK responses when `continueOnError` flag is `true`.
- When `continueOnError` flag is set to `true`, `requestId` is not present for failed requests.
- The absence of `requestId` makes it difficult to debug and troubleshoot these failed requests effectively.
- `requestId` will be present for `detokenize` failure responses when `continueOnError` is `true`
- `requestId` will be present for `insert` failure responses when `continueOnError` is `true`
- The changes were tested manually.
- Modified unit tests to check for presence of `requestId` in failed request responses when `continueOnError` is `true`
=> SK-1890 Add request Ids in response for continue on error failures

samples/src/main/java/com/example/connection/InvokeConnectionExample.java, samples/src/main/java/com/example/vault/ClientOperations.java, samples/src/main/java/com/example/vault/CredentialsOptions.java, samples/src/main/java/com/example/vault/DeleteExample.java, samples/src/main/java/com/example/vault/DetokenizeExample.java, samples/src/main/java/com/example/vault/GetExample.java, samples/src/main/java/com/example/vault/InsertExample.java, samples/src/main/java/com/example/vault/QueryExample.java, samples/src/main/java/com/example/vault/TokenizeExample.java, samples/src/main/java/com/example/vault/UpdateExample.java
This PR improves the samples for Java SDK `v2`. 
- The current samples didn't cover some scenarios.
- The current samples weren't following proper variable naming and were not fully ready to use.
- The samples should cover all the scenarios of the SDK.
- The samples should be ready to use and should follow proper variable naming.
=> SK-1959 Fix Java Samples

src/main/java/com/skyflow/errors/ErrorMessage.java, src/main/java/com/skyflow/errors/SkyflowException.java, src/main/java/com/skyflow/utils/Constants.java
This PR fixes the error handling for few scenarios in Java SDK v2.
- The error handling for few flows was not working as expected.
- The unexpected errors could lead to confusion and would be hard to debug.
- The error handling works as expected.
- Tested manually
=> SK-1969 Fix error handling for certain scenarios

README.md, samples/src/main/java/com/example/serviceaccount/BearerTokenExpiryExample.java
- Why are you making the change?
-  To add edge case while making a API call with token.
- What is the intended outcome?
- To inform customer about the token expiry edge case.
=> SK-2003: Add bearer token edge case

samples/src/main/java/com/example/DeleteExample.java, samples/src/main/java/com/example/GetExample.java
Added example of `Flow DB` vaults `get`  &  `delete` records in java sdk.
- To try out the various operation on `Flow DB` vaults.
- By this users can try out the various operation via sdk on `Flow DB` vaults.
- Locally
=> SK-2030 flowdb sdk with get, delete example

src/main/java/com/skyflow/VaultClient.java, src/main/java/com/skyflow/errors/ErrorMessage.java, src/main/java/com/skyflow/logs/ErrorLogs.java, src/main/java/com/skyflow/logs/InfoLogs.java, src/main/java/com/skyflow/utils/validations/Validations.java, src/main/java/com/skyflow/vault/controller/VaultController.java, src/main/java/com/skyflow/vault/data/FileUploadRequest.java, src/main/java/com/skyflow/vault/data/FileUploadResponse.java, src/test/java/com/skyflow/VaultClientTests.java, src/test/java/com/skyflow/vault/controller/VaultControllerTests.java, src/test/java/com/skyflow/vault/data/FileUploadTests.java
This PR adds changes for supporting file upload operation in Java SDK v2.
- Java SDK v2 did not support for uploading files.
- User should be able to upload file using Java SDK v2.
- Added unit tests and tested manually.
=> SK-2128 Add support for uploading file in Java SDK v2

src/main/java/com/skyflow/errors/SkyflowException.java, src/main/java/com/skyflow/serviceaccount/util/SignedDataTokenResponse.java, src/main/java/com/skyflow/utils/Constants.java, src/main/java/com/skyflow/vault/connection/InvokeConnectionResponse.java, src/main/java/com/skyflow/vault/controller/ConnectionController.java, src/main/java/com/skyflow/vault/controller/DetectController.java, src/main/java/com/skyflow/vault/controller/VaultController.java, src/main/java/com/skyflow/vault/data/GetRequest.java, src/main/java/com/skyflow/vault/data/GetResponse.java, src/main/java/com/skyflow/vault/data/InsertResponse.java, src/main/java/com/skyflow/vault/tokens/DetokenizeData.java, src/main/java/com/skyflow/vault/tokens/DetokenizeResponse.java, src/test/java/com/skyflow/errors/SkyflowExceptionTest.java, src/test/java/com/skyflow/vault/connection/InvokeConnectionTests.java
**Why**
- The Java SDK has some inconsistencies compared to the Node and Python SDKs.
**Outcome**
- Improved consistency across SDKs.
=> SK-2181: Fix inconsistencies

.github/workflows/beta-release.yml, .github/workflows/release.yml, pom.xml
This PR updates POM config and release workflows to migrate from OSSRH to central publisher portal
- OSSRH portal is shut down, so we need to migrate to central publisher portal
- The release pipelines should not break and we successfully migrate from OSSRH to central publisher portal
=> SK-2207 Update release workflows and POM

v3/src/main/java/com/skyflow/utils/Utils.java, v3/src/main/java/com/skyflow/vault/controller/VaultController.java
=> SK-2258 synchronized errors

v3/src/main/java/com/skyflow/utils/Utils.java, v3/src/main/java/com/skyflow/vault/controller/VaultController.java
Fix the error response handling
=> SK-2258 fix the error response handling

v3/test/java/com/skyflow/vault/controller/VaultControllerTests.java
**Why**
- A new insert interface has been introduced in the v3 Java SDK, but there are currently no unit tests covering it.
**Outcome**
- Add unit tests to cover all validations and scenarios for the insert flow.
=> SK-2276: Add unit tests for insert flow for v3

common/src/main/java/com/skyflow/errors/ErrorMessage.java, common/src/main/java/com/skyflow/utils/BaseUtils.java, common/src/main/java/com/skyflow/utils/validations/BaseValidations.java, v3/src/main/java/com/skyflow/VaultClient.java, v3/src/main/java/com/skyflow/utils/validations/Validations.java
To pass vault url from the env variables
- Currently only cluster id and env are passed and the url will be constructed with these values
- But there is no feasibility to pass vault url directly
- So  made code changes to take it from the env variables and override the one that is constructed by cluster id
- The url passed from env variables should override the one that is constructed with cluster id
- tested in local
=> SK-2286 take vault url from env and override

common/src/main/java/com/skyflow/errors/ErrorMessage.java, common/src/main/java/com/skyflow/logs/ErrorLogs.java, v3/src/main/java/com/skyflow/VaultClient.java, v3/src/main/java/com/skyflow/utils/validations/Validations.java, v3/src/main/java/com/skyflow/vault/controller/VaultController.java, v3/test/java/com/skyflow/vault/controller/VaultControllerTests.java, v3/test/java/com/skyflow/vault/data/InsertTests.java
This PR fixes the issue where upsert operation was not working as expected even when upsert related options were passed in insert request. 
- If upsert options are passed, then upsert operation should take place for records that match upsert critieria.
- When upsert options are passed, then upsert operation will take place for records that match upsert critieria.
- Tested the changes manually for upsert and verified that upsert operation is taking place.
=> SK-2289 Fix upsert operation not working issue

README.md
=> SK-2302 Updated samples link in readme

.github/workflows/release.yml, samples/pom.xml, samples/src/main/java/com/example/vault/BulkInsertAsync.java, samples/src/main/java/com/example/vault/BulkInsertSync.java, samples/src/main/java/com/example/vault/BulkMultiTableInsertAsync.java, samples/src/main/java/com/example/vault/BulkMultiTableInsertSync.java, v3/pom.xml, v3/src/main/java/com/skyflow/utils/Constants.java, v3/src/main/resources/sdk.properties
- To get the SDK version as prefix for the logs
- The version was dynamically hard coded before in constants file
- Now we get it from the project metadata
- The logs should have the Skyflow Java version as prefix
=> SK-2315 add version as prefix to logs
